### ISSUE TITLE
Missing architectures

### ISSUE THREAD

**Issue by Joy-less** [godotengine/godot-cpp-template#88]
### Godot version

v4.4.1

### godot-cpp version

v4.4.1

### System information

Windows 11 Home

### Issue description

The default `builds.yml` file seems to be missing some architectures.

```yaml
matrix:
  # A build is made for every possible combination of parameters
  # You can add or remove entries from the arrays of each parameter to custimize which builds you want to run
  # See https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/running-variations-of-jobs-in-a-workflow
  target:
    [
      { platform: linux, arch: x86_64, os: ubuntu-22.04 },
      { platform: windows, arch: x86_64, os: windows-latest },
      { platform: windows, arch: x86_32, os: windows-latest },
      { platform: macos, arch: universal, os: macos-latest },
      { platform: android, arch: arm64, os: ubuntu-22.04 },
      { platform: android, arch: arm32, os: ubuntu-22.04 },
      { platform: android, arch: x86_64, os: ubuntu-22.04 },
      { platform: android, arch: x86_32, os: ubuntu-22.04 },
      { platform: ios, arch: arm64, os: macos-latest },
      { platform: web, arch: wasm32, os: ubuntu-22.04 }
    ]
  target-type: [template_debug]
  float-precision: [single, double]
  include: # Also build a release version for these specific targets. Remove if you add template_release above.
    - target: { platform: linux, arch: x86_64, os: ubuntu-22.04 }
      target-type: template_release
      float-precision: single

    - target: { platform: linux, arch: x86_64, os: ubuntu-22.04 }
      target-type: template_release
      float-precision: double
```

I think it should be more like:

```yaml
matrix:
  # A build is made for every possible combination of parameters
  # You can add or remove entries from the arrays of each parameter to customize which builds you want to run
  # See https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/running-variations-of-jobs-in-a-workflow
  target:
    [
      { platform: linux, arch: x86_64, os: ubuntu-22.04 },
      # { platform: linux, arch: x86_32, os: ubuntu-22.04 }, # doesn't work for some reason
      # { platform: linux, arch: arm64, os: ubuntu-22.04 }, # doesn't work for some reason
      { platform: linux, arch: arm32, os: ubuntu-22.04 }, # NEW
      { platform: windows, arch: x86_64, os: windows-latest },
      { platform: windows, arch: x86_32, os: windows-latest },
      { platform: windows, arch: arm64, os: windows-latest },
      { platform: macos, arch: universal, os: macos-latest },
      { platform: android, arch: x86_64, os: ubuntu-22.04 }, # NEW
      { platform: android, arch: x86_32, os: ubuntu-22.04 }, # NEW
      { platform: android, arch: arm64, os: ubuntu-22.04 },
      { platform: android, arch: arm32, os: ubuntu-22.04 },
      { platform: ios, arch: arm64, os: macos-latest },
      { platform: web, arch: wasm32, os: ubuntu-22.04 }
    ]
  target-type: [template_debug, template_release]
  float-precision: [single, double]
```

Note there's also a spelling error fix with "custimize"->"customize".
